services:
  backend:
    container_name: project_gate_backend_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/project_gate
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: project_gate_db_dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_gate

volumes:
  db_data_dev:
